import collections


class Solution:
    def predictPartyVictory1(self, senate):
        """
        :type senate: str
        :rtype: str
        """
        def helper(list_senate, now_index, type, other):
            if list_senate[now_i] == type:
                for i in range(now_i+1, len(list_senate)):
                    if list_senate[i] == other:
                        list_senate[i] = '_'
                        break
                else:
                    for i in range(now_i):
                        if list_senate[i] == other:
                            list_senate[i] = '_'
                            break

        list_senate = list(senate)

        now_i = 0
        while True:

            if now_i == len(list_senate):
                now_i = 0

            helper(list_senate, now_i, 'R', 'D')
            helper(list_senate, now_i, 'D', 'R')

            if 'D' not in list_senate:
                return 'Radiant'

            if 'R' not in list_senate:
                return 'Dire'

            now_i += 1

    def predictPartyVictory(self, senate):
        """
        :type senate: str
        :rtype: str
        """
        senators = collections.deque()
        D_senators_count, R_senators_count = 0, 0
        D_bans_count, R_bans_count = 0, 0

        for senator in senate:
            if senator == 'R':
                R_senators_count += 1
            else:
                D_senators_count += 1
            senators.append(senator)

        while D_senators_count and R_senators_count:
            if senators.popleft() == 'R':
                if D_bans_count <= 0:
                    R_bans_count += 1
                    senators.append('R')
                else:
                    R_senators_count -= 1
                    D_bans_count -= 1
            else:
                if R_bans_count <= 0:
                    D_bans_count += 1
                    senators.append('D')
                else:
                    D_senators_count -= 1
                    R_bans_count -= 1


        if D_senators_count:
            return 'Dire'

        if R_senators_count:
            return 'Radiant'






if __name__ == "__main__":
    sol = Solution()
    print(sol.predictPartyVictory("RDD"))
    print(sol.predictPartyVictory("RDDDRRR"))
    print(sol.predictPartyVictory("DRDDDDRRDDRRRRDDDRRRDDDRRDRRDDRDDDRRDRRRRRDRDDDRRDRDRDRDRRDDDRDRDRRRRDDDDDDRRDDDDRRDDDRRRRDDDDRDDRDRRDDDDRDDDDDRRRRRDRDDRDDDDDRDRDDDRRDDRRRRRRDDDRDDRRRDRRRDDDDRRDRDDRRDDRDDDRRDRRRDRDDDDDDRRDRDDDDDRDDRRRRDDDDRDRDRRDRDDRDRDDDRRDDDRDDDRRDDDDRRDRRDDDRRDDRRDDDRRDDDRDRDDRRRRDDDRRDDDRRDRRRDDDDDRRDRRRDDRRDRRRDRDRRRRRDDDDRRRRRDRDDRDDRDDRDRDRRDRRRRRRRDRDDRDRRDDRDDDDDDRDDDRDDDDRRDRRRDRRDDDDDDRDRRRDRRRRDDRRRDRDDDDDRRDDRRRDDRRDDRRRRRRRDDDDDDDDRRDRDRDRRRRRRRRDDRRDRDDRRDRRRRDRDDDDRDRDDRRRDRDRRDDDDDRDRRRRRRDDDDDRDDDDDRDDDDRDDDDRRDRRDRRRRRDRRDDDDRRDRDDRRRRDRRDRDRRDRDRRRDDRRDRDDDDRDRDDDRRRRDRRDDDDRDDDRRRDRRDRRRDDRDRDDRRDRDDRDDRRRDDRDDDDDDDRDDRRRRDRRDRDRDRDRRRDRRDRRRDRDDDRRDRRDDDRDDRDRRDRRDDRRRDRRDDRDDDDRDDRDRRRRRRDDDRDDDRDRRDRDDDRDRDRRDDDRRDRRDRDDRDRRRRRDRDDRRDDDRDDRDDDDDRDDRDRDRRRRRRDRDRRRDDRRDRRDRDDDDRRRDDRDDDDRRDDDDDDRRDDDRDDRDRDDRRRDDDDDDDDRDRRDRDRRDDDDRRRRDRDRRDDRRRDDRRDRDRRDRRDDDDDRRRDDDDDDDDDRRRRRRDDRRDDDRDRDDDDRDDRRRDRRDRDRRDDDRRDRDRRRRRRDDRRDRDRRRRRRDDRDDRRDDRDDRRDRRDRRRRDDRDDDDRRRDRRDDDDDDRRRDRRDDRDRDRRDRRDDRDDDDDRDDDRDRDDDDRDDDRRDDDDDDRRDRDDDDDDRRDDRRDDRDRRRRDDRRDDRDDDRRRDRRRRRDDDDDRDDDRDRRRDDDRDRDRDRRRRDDDRRDDDDRRRRRDDDRDDDDDDDRRRRRRDDDDRDDDRRDRDRDRDRRRDRRDRRDDDDDRDDDRDDRDDDDDDRDDDRDDDDRDRRRDDDDDDRRDRDDRDRDDDDRRDRRDRRDDDRDDDRRDDDRDRDRDDDRDRDDDDDDRDDRDDRRDRRRDDRDRDDRDRRDRDDDDDRRDRDRRRDDRRDRRDDRDDRRRRRDDRRRDRRRRDRDDDDDRDRRRRRDRDDRDDDDDDDRRRRRDRRDRRRRDRRDRDDRDRDRRDRRDRRDRDRDDDRRRDDRDRRDDDRDRDRRRDDRRRRRRDDRDDRRRDDDRRDDDDRRRDRDRRRRRDDDRRRRDRDRDRRRRRRRRRDDRRRDDDRRDDRRRRDRDRRRRDRRDDRRDDRRDDRRRRDRRDRRRRRRDRRRRRRDRRRRDRRDDRDRRRDRRDRDDDDDRDRRDRRRDRRDRDRRRRDDRRRDDRRRDRDRDRRDRRRDRRRDDRRRRDDDRRDDRRRDRRRDDDRRDDRDRDDRRDRRDRRRRDRDDDRDDDRRDDDRRRRDRRRDDRRRDRRDRDDDRDRRRDDRDDRRRDDDRRDRRDRDRDRRDRDRDDRDRDDDRRDDDDDRDRRDRRDDDRDDDDDDDDDRRRDDRRDRRDRRDDRRDRRDDDRRRDRDRRDRDDDDDRDDDDDRDRRRDDRRDRDRRDDDRRDDDDDRRRRRRRRRDDRRRDRRRRRRDRRRRDDRDRDRDDRDRDDDDRDRRDRRDRDRRDDRRRDRRRDRDRDRRRDDRRRRRRRDDDDRDRDDDDDRRRRRRRDRDDDDDDRRDRRRRRDDRDRDDRRRRDRDDRDRDDDDDRDRRRRDDDDRRRDDRRDDDRDRDDRDDRRDRDRRRRRDRRRRRRRDRDDRRDDDRRRDRDDDRDRDDDRRRRRDDRRRDDRRDRRDDDRRDDRDDRDRDDRDDDDRDDDDDDDRRDRDRDRDDDDDDDDDDDRDDDDDRRRDDDRDRDDDDDRDDRRRDDRDDRRRDDDDDDDDRDRDRDRRRDRDDRRDDRDRRDRDDRDDRRRRDDDRRDDDRRRRDRRDRDDRDRDDDDDRDDDDRRRDRDDRDRRDDDDDRDDDRDRDRDDRDDRRRDDDDDDDRRDDDDRRDDRDDRDRDDDRDRRRDRRDRDRRDRRDDRDDDDRDDRDDRRRDRDDDDRRDRDDDDDDRRDDDRDRRRRDDDDRRDDRDDRRRRRRRRDRRRDRRDRDRRRDRRRDDDDRDDDDDDDDRRRRDDDRRDRDDRRDDDRDDRDRRDDDDRRRRRRRRRRRRDRDRRRRDDDDDDRDDRRDDRDRRDRRDDRDRRDRDDRDDDRDRDDRRDRDRRDRRDRDRRDRRDDRRRRRRDDRRDRRRRRDDDRRDRDDRDDRRRRRRRRDRRDDRDDDRRRRDRDDDDDRDRDDRRDRDDRDRDDDDRDRDDRRDRDDDDRDRDDRRRRRRDRRRRDRDRRRDRDRRDRDRDDRRDRRDDRDDRRDDDRRDDRDRRRDDDDRDRDDDDRDRDRRDRDRDDDDRDRDRRRDDRDDDRDDRRDRRDDDRDDRRDRRRRRRRDDDRDRRRRDRDRRRRDDDRDRDRRRRRDRDDDDRRDDDRDRDDDDDDDRDRDDDDDRDDRRDRRRRDRDDRDDRRDRDDDRDDRRDDDRDRDRRDRDRRDDDRDDRDDDDDRRDRRDDRDRDRRRRDRDRRDRRDDRRDDRDDRRRDDRRDRDDDRRDDRDDDRDDRRRDRDDDRRDRDDRRDRRDDDDRDDDRRDRDDDRDDRRRRDDRRRDRRRDDRRRRRDRRRDDDRDRRRRRDDRRDDDRDDRRDRDRDRDDDRRRRRRDDRRRDDRRRDRRRRDRRRDRDDRRDRDRRDRDRRRDDDRDDDDRDRDDDRRDDDDRDDDRDDRRRRDDDDRDDRDDRRDDRDDDRDRDRDDRRDRRRRDDRRDDDRRRRDDDRDDRDDRRRDRRDRRRDRRRRDRDRRRRDDRRDRRRDDDRDDDRRRRDRRRDRDDRDRDRDDRDDRRRDRRRDDDDDRRDDDDDRDRRRRRRRDRDRRRRRDDRDRRRRRRRRRRRRDRDDRDRRDRDDRRRRDDDDRDRRRRDRRDRDRDDRRDRRRRDRRRDRRRDDDDRRRDRRRDRDDDDRRDRDDDDRRDRRRRRDRRDDRRRRDRDRRRRRDDDDRDRDRRDDRDRDRDDDRRRDDDRRRRRRRRDDRRDRRRRRDRRDDDRDRDRDRRDDRDRRDRDRRDDDDRDRDRDDRDRDRRDDRRRDDRRDRRRRRDRDRDRDDDRRDRDRDRRRRDDDRDRRDRRDRRDRRDRRDRRDRRDDRRRRRRDRRRDRDRDDRRDRDDRDRRDRRDRRRDDDDRRDRRDDDRRRDDDDRRDDRDDDRDRDDDDDRRDRDDDRDRRDDRDRRRRRRDDDRDDRDRDRDDRRRDDDDDRRDRRDRDDDRRRRDDRDDRDRRDRDRRRRDDRRDRDDDDDRDDDRRDRRRDDRDDDRRRRRRDRDRRDDRDRRRRRRRDRRDDDRDRDRRDDDDDDDDRRRDDRRDRDRDRDRDRDRDRRDDDDDRDRRRRDDDRRDDRDRDDRRRDRDRRDDRRDRRRDRRDDRDRRDRDRRRDDDRDDDRDDRRDDRRRDRRDRDRRDRDDDDRDRRRRDDRRRRDRDRRDRDDDDRRRRRDRDDDDDDDDDDDRDDRDDDDRRRDDRRDRDRRDDDDDDDRDRDRRRRRRDDRRRDRRDRDRRDRRDRDDDRDDRDDRRRRRDDRDDDDDRRRDRDRRRDDDRDRRRRRRDDDRRDDDDDRDDRRDRRDRDRRDRDRRRDRRDRRDDRRRDRRDRRDDDRDDRRRDRRRRRDDRDDDDDRDDRDRRRDRRDRDRDDRDDRDRDDDDDRRDRDRRDRDDDRDDDDRDRRDRRRDRDRRDDRDRRDRDRRRRDDDRRRRDDRRDDRDDRDRDDDDRRDDDDRDRRDDDDDDDDRRDDDDDDDRDDRDRRRRRRRRDRDDDDRDDDRDRRDRDDRDDRRDDDDDRRDDDDRDRRRDRDDDRRRDDDDRRRRRRDRRRRRRRDRRRRDDDDDDRRRDRRRRDRRDRRRDDRRDDRRRDRRRRRDRDRDRDDDDDRDRRRDRRRDRDRDRRRDDDDRRDRRRRDRRRRRDRDDDDRRDRDRRDDDDRRRDDDRDDDRRRRRDDDRDDRRRRDDDRRDRDRRDRDDRDDRDRRDDRRRRRRRDDRDDRRRRDDRRRRDDRDRDDDRRRRRRRDRRDDDDRRDRDDDRRRDRRDRRDDDRDDRDDRRDRDRRRRDDDDRRDDRRRDDRRDRRRRDDRRRDDDRRDDDRDDDDRRRRRRDDRDRRDRDRRRRDRRRDDRRRRRRDDDDRDRDDRDRDDRDRRRRRRRDRDDDRRDDRRDRDRDDDDDRDDDRDDRDDRDDRRRDDRDRDDDRRRDDDRRDDRDRDRDRRDRDDRRRRDRDDDDDRDRDRDDDRDDRDDRDRDRRRDRDDRRRRRRRRDRRDRRRRRDRDRDRRDRRRRRRDRDDRDDRDRDDDDDDDDRDDRDDRDDRDDDDRRDRRRDRRDRRRDRDRRRRDRRDDDDDRDDDDRRRRDRRRRRRDDRRRDRRDDRDRDRDDRDDDDRDDDDDRDDRRRRRRDDRRDDRDDDDDRDRRDDRDDRDDRDDDDDDDDRDDRDDRRDRDRDRDRRRRRRDDDDRRRRDRDDDRDDRDRRDDRRRDRDRDDRDRDDDRRDDDDRDDRRDDDDRDDRRDRDRRRRRDDDRRDRDDDRRRRRRDDDRDRDDDDRDDRRDDDRDRRDRDRRDRRRDRRRRRRRRDDRRRDDRDDDDRDRRDRRDDDRRDDRDRRDRDRDDDDDDDDRRRRRDDDDDDRRRRRDDRDDRRDRRDRDRRDRDDDRDRDDDDRDRRRDDRDDDDRDRRRDDDRRDRDDRDRRDRDDDRRDDDRRRDDRRRDDDRDRDRRRDRRDDRDRDRDRDRDRRDDDDRDRDDDDDDRRDDRRRDDDDRDRRDDRRDRDRRRDDRDRDDDDDDRRDRRDDRDRRDRRDDRRDDRRRRDDDRRDDRDRRDDRRDDRDRDDRRRDDRDRDRDRRDDRRDDRRRDRRDRRDDRDRDDRDRDDRRRDDRDDDRRDRDRRRRRDDDDRRDDDDDDDDDDDDDRDRRDRDRDRDRDRRRDRDRRDDDDRDDDDDDRDRRDRDDDRDDRDDDDDDRDDDDDRRDRRDRRDDDRRDRRDRRDRDDDRDRRDRDDRDRDRDDRDDRRRDDRRDDDRRRDDDDDDDDRDDDRDDRRDRDRDDDRDRDRDRDDRDRDRRRRDRDDDDDDRDDRRRRDRRRRRRDRRDRDRDRRRDDRDDDRRRDDRDDRRDRRRDDDDDDDRDDRDDRRDDDRRRRRDRDRDDRDRRDRDDRDRDDRDRRRRDRRDDRRDDRDRDDRRRDDDDDDRDDRDRRRDRDDDDDDDDDRRDDRRDDDDRRDDDDRRDDRRRRDDDDRRRRRRDDDRRRRRRDDDRDRRDDRDRDDDRRRRRDDDDDRRDRDDRRDRDRRRRDRDRDDDDRRRRDRRRDRRDRRRDRRDDDRDRDDRDDRDDDDDRDRDRDDDRRDRRDDDDRRRRDRDRDRDRRDDRDDDRDRDRDRRRRRDDRDRDDDRDDRRDRRDDRDRRRDDRDRRRRDRRDDRRRRDDDDDDRDRDDRRRRRDDRRRRRRRRRDRDRRRRRRRDRRRDDRDDRRRRDDRDRDDDDRDRRRDDDDRRRRRRDRRDDRRRRRRRRRDDRDDRRDRRDRRRDRRRDDRDRDRDRRDDRRDDRDRDDDDDRRRRRRDDRDRRRRDRRDRRDRRRRDDRRDRDRRRDDRDRDRDDDDRRDDDRDRRRDDDDDRDRDRRDDRDDRDDDDDDRDDDDDDDDDRRRDRDRDRRDDDRRRDRDDDRRDDDDRDDRRDDRRRDDDDRRDRDDRDRDDRRDRDDDDRDDRDRDDRRRRRRDDDRRDDRDRRRDDRDDRDDDDDRRRRRRRDRDDRRDDDDRRDRRDDRDDDDDRDDRDDDDRDRDDDDDDDRRDRDDDRDRDDRRRDRDDRDRDRRDRDRRRRRDRDDDRRDRRRRRRDRRRRDDRDDDDRRDRDDDDDDRDDDRRRDRDRRRRRRDDDDDRRDDRDDDDRRRDDRRRRDDRDDRDDRDDDDRRDDRDDDDDRRDRDDRRDRDDDDRRRDRDRRRRDRDDRRDRDDDRDDRDDRDRRDRDDDDDDRDRRDRDDRRRRRRDRRDDRRRRDDDDDDDDDDRDDRRRDDDRDRRDDRRRDDDRDDRDDDDRRRRDDRRDRRDDDRDRRDRRDDRRDDRRDRRDDDDDDRDDRDRRDRDDDDRRRRDDDDDRDDDRDDRRRDDDDDRRRRDDDDRRRRDRRRRRDDDRRRDRDRRDDDDRRRRRRRRRDDDDDDRRRRDRRDDDRDRDRDDRDRDRRDDRRDDRDRDRDRDRDDDRDRRDRDDDRRDRDDRDRRRRDDDRRDRDRRDDRDDDDRRDRDDRDDDDDDRDRRRRDRRRDRDDDRDRDDDRDRRDRDRRRRRDRRRDRDDRRRDRRDRRDDDRDRDRRDDRDRRDRRDRRDDDRRDDDDRRDDDRRDDDDRDDDDDRDRDDDRRRDDRDDDRRDRDRDDRRDDRDRRRRRDDDRRDDRRRRRDDRRDDRDRDDDDDDRDRRRDRDRDRRRDDRDRDDRDDDDRRRRRRRRDRRDRRDRRRDDRRRDDRRRRDDRRDDDDRDDRRDRRRRDDDDDRRDDDRRRDDRRRRRDRDDDDRDRRDDDDRDDRDDDDRDRRDDDRRRDDRDRRRRRRDDDDDDRRRDDRDRRRRRRDDDDDDRRDDDRDDRRRRDRDRRRDDRRRDRRRDDDRDRRRDDRRDRDRDRRRDRRDRDRRDRDDRDRDRDRRRDDDRDDRDRRRDRDDRDDRRDDRDRRRDDRRRDRDDDRDDRDRDDDDDRRRRDDRRDRRDDDDRDDRDDDRDDRRDDRRDDDRRDDRDRRRDRRRRDRDDRRDDDDDRRRDRRRRDDRRRDRDDRDDRDRRRRRRDDRRRDRDRRRDDDDRDDRRDRRRRRDRRRDRDDRDRDRRDRRDRRDDRDDDRDRRRRDRDDDRDDDDRDDDRDDRRDDRDRRRDDDDRRRRRDDRRDDRDDRRRRDRRRRRDDDDRDRDDDDRRRRDRDRDDDRRDDRDRRRDDRRRRDRRDDRDDDRDRDRRDRRDRDDRDDRRRRDDRDDDRDRRRDRRRDRDRDRRRRDDDRRRDRRDRDRDDDRRDRDRRRDDDRDRRDDDRRRRRDDRRDRRDRDRDRDRRRDDDDDDRDRRRDRRRDRRRRDDDRDRDDRDRDRRRRRRRRRDDRDDDRRRRDDDDDRRRDRDDRRRRDDDDRDRRDRRRRDRRRDRRRRRDDDRRDRDRDRRRRDDDDRDRDRRRRRRDDDRRRDRDRRRRRDDRRRRDRRDRRRRDRDDRRDRRDDDRRDRDDRRDDDRRDDRDRDRRDRDDDDRRRRDDDRRDRDRRDDRRDDDDDDRRRRRRRRRRDDDDRDRDRRRRDDRDRDRRDDRDRRRRRRRRDRDRRDRRRRDRRDDDRRRDDRRDRDDDDDRRRDRRRRRDDDRDRRRDDDDDRRRDRRDRRRRRRRRDDRDDDDRRRRDRDDRDDDDDDRDDRRDRRDDDDDDRRRDDRRRDRRDDRRRRRDDRDRRDDRRRDDDDRDDDDDRDDRRRDDRRRDRDDRDDDRDDDDRDDDRRDDRRDRRRRRRDRRDDDDRDDRRDDRDDDRRRRRDRDRDRRDRDDRDDDDDRRRRRRRDRRDRRDDDDDDRDDDDDDDRDDRRDRDRRDRDRDDDDDDRRRDDDRDDDDRRDDRRDDDRRDDRRRDRDRDDDRRRDDRRRRDRRRRRDRDRDDDDRDRRDRDRRRRDDRDRDRDDRRDRDRDRDDDDDDDDRDRDDRDRDRDDRDRRRDRRDDDDRDDDRDDRDDRRDDDDRDRDDDRRDRDRRDRDDRRRDDRDDDRRRRRRDRDDDRRRRDDDDRDRDRDRDDDDRRRRDDRRRDDDRRDDRDDDDRRRRDDRDDRRRRRDDDDRDDDDDRRDRDRDDDRRRDDRDDDDDDDRDRRRRDDRRRRRDRRDDRDRRDRDRRDRDDRRDDRDDDRRDRDDDDDRRRRDRRDRRRDRRRRDRDRDDRDRDDRDRDRRRRDDRDRDDRRRRRDRRRDDDDDRDDRRDRDDDRDDRDRRDRRRRDRRDRDDRRDDRRDDRDRDDDRRRRRDRDDRDRDDRDDRRRDRRRDRDDRDRRDRRDRRDRRDRRDDRDRDRRRDRRDRRRDDDDDRRDDDDRRDRDRDRDDDRDDDDRDRDDDRRDDDRDRDDRDDDDDDRDRDRDRRRDRRDDDRDRDRRDRDRDRRDRRRRRRDRRRDRRDRRDDDRRDRDRDRRDDRDRRRRDRRRRDDRRRDRDDDRRDRDRRRRRDRRDRDRRRRRDRDDDRRDRDRDDDDDRDDDRRDRRDRDRDDRRRDDDRRRRDDDRDDRRRRRDRRDRDRRDRRDRDDRRRRRRRRDDRDDDRRDDDDRDDRDDDRRDDRDDDDDDDDRDRDRDRDDRRDDRRDRDDDDDRRDDRRRDDDRDDDDRDDRRRRDDRRRRDDRDRDDDDRDDDDDRRDDRDDRDRDDRRDRRDDDRDRRDDRDDDRRDRDRDRRDRDRDDDDRRDRDDDDDRDRRDDDDDDRRRDDRRDRRRRDRRRRRDRDDRDDRRRRRRDDRDDDDRDRRRRDRRDRDDRDRDDRDDRRDDDRDDRRDRRDDRRRRDDRRDRDDDDRRRDDRDDDDRRRDDRRDDRDRDDRRRDDRRRRRDRRDDRDDDDRRDDDDRDRDDDDRRDDDDDDRDRRRRRRRDRDDDRRRRDDRRDRRDDRDDRDRDDDRRRRRDDRRDRRRRRRDDDDRRDRRDRDRDDDDDDRDRRRRDRDDDRRRDRDRRDDRDRDDRRDRDRDRRDRDRRDRRRDDRDRDDRDRRRRDRRDRDDDRRDRRRDRRDRRDDDRDDRRRDRDRDDDRRRRDDRDRDRDRDRRRDRRRDDDDRDRDRDDDRRDDRDRRDDRRRRDRRRDDDRRDDRRRDDRDRDDRRDRDRRDDDDDRRDDDDRRRRRDDDRDDDRRRDRDDRDDDDRRRDRRRRDDRRDRRDDRRRRRRRRRRDDRRDDDRRDRDDDRRDDDDDRRDDRDRDRDRRRRDRRRRDDRDDRDDDDDDDRDDDRRRRDDRDDDRDDRRDRRRDRRRRRDDRRDRRDRDDDDDRRRRDRDDRRRDDRDDDRDDRDRRRDDRRDDRDRDRRRDDRRRDDRRDDRDDDDRRRDDDRRRDDRDDDDDRRRDRRRRRRRDDDDDDRDDRDRDDDRRRDRDRDDDRDDRDRDDDRRRRDRRRRRRRDDRRDRDRRDDDDDRRRRRRDRDDRRRDRDDRRDDRRRRDRRRDRDDRRDRRDRDRDDRDRRRRDDRDDDDRRDDDRRRRDRRDRDRDDDDDDRDRRRDDDRRRDRRRDRDDRRDRRDRDDRDDDRDRRDDDDRRDRRDRRDRDDRRRDRRRRRDDDDRRRRDRDDDDDDRDRDRRRDDRDDDRDDDDDRDDRRDRDDRRDRRRRRRDRRRRRRDDDRRDRRRRRDDDRRDDDRRRRRRDDDRDDRRRDRDRRDRRDDDRRRRDDRRDRRRDRRRDRRDDDRDRDDDRRRRRRDRRRDDDDRRDDDDRRRDDRRDDRDDRRDDDRDRDRDDDRRRDRDRDRDRRRDDRDDRRRDRDRRRRDRRRRRRDDRRRDDRDRDDRRDRDDDRDRRDRRDDDDDDRDRDDDDDRRRDDRDRDRRDRDRRRDRRDRRRRRRDDRRDDRRDDDRRRDDDDDRDDDRDRRRDDDDDRDDDRRDRDRRDDDRRRDRRDDRDDDDRDDRDDDDDRDDRRRRDDDRRRRDRDRDRRRDDDRDDRDDRDDDDRDRRDRDDDDRDDRRRRRRRDRRDRRRDDDRDRRDRRDRRDRRRDDDRRDDDRDDRDDDDDRRDDRRRRDDRRDRRRDRRDRRDRDRDRDDDDRRDDD"))  # DRRRRDDD -> DRRR -> RR

